# Generated by Django 3.1.5 on 2021-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210130_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('Hungary', 'Hungary'), ('United States', 'United States')], max_length=50),
        ),
    ]
