# Generated by Django 3.1.5 on 2021-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, upload_to='static/pics/bg_pics/'),
        ),
    ]
