# Generated by Django 3.1.5 on 2021-02-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210205_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/pics/profile_pics/', verbose_name='Profile picture'),
        ),
    ]
