# Generated by Django 3.1.7 on 2021-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
