# Generated by Django 3.1.7 on 2021-03-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210315_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
